# Generated by Django 4.1.5 on 2023-02-04 19:55

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Недопустимый домен.', regex='rambler.ru,')]),
        ),
    ]
