# Generated by Django 4.1.5 on 2023-02-04 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_birth_date_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Недопустимый домен.', regex='@rambler.ru')]),
        ),
    ]
