# Generated by Django 4.1.5 on 2023-02-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='author',
            new_name='owner',
        ),
    ]
